// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbxKwiOKqlkQZQHlXomH4UrYbOD-FMnQU',
    appId: '1:130845731368:android:d4257e2a660a1f4a9fa31d',
    messagingSenderId: '130845731368',
    projectId: 'fruit-ninja-bfc40',
    storageBucket: 'fruit-ninja-bfc40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHUUD38_r0vgJUzTWc7RKyaAlkb8dkya0',
    appId: '1:130845731368:ios:e90e114ecc1637e89fa31d',
    messagingSenderId: '130845731368',
    projectId: 'fruit-ninja-bfc40',
    storageBucket: 'fruit-ninja-bfc40.appspot.com',
    androidClientId: '130845731368-4tvr0nl6ilotke9dvq9okljc0l9fd011.apps.googleusercontent.com',
    iosClientId: '130845731368-129984r2159osikdeba3u9290pu9qh61.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyAssistant2608',
  );
}
